services:
  app:
    build: .
    container_name: barcode-api
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - vendor_volume:/var/www/html/vendor

volumes:
  vendor_volume: